package hashpp.bills.model;
// Generated Dec 2, 2019 12:32:32 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * BillPayments generated by hbm2java
 */
@Entity
@Table(name="bill_payments"
    ,catalog="billpay"
)
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(value = {"createdAt", "updatedAt"},
        allowGetters = true)
public class BillPayments  implements java.io.Serializable {


     private Integer pmtId;
     private Payee payee;
     private Date pmtScheduleDt;
     private BigDecimal amount;
     private String pmtStatus;

    public BillPayments() {
    }

    public BillPayments(Payee payee, Date pmtScheduleDt, BigDecimal amount, String pmtStatus) {
       this.payee = payee;
       this.pmtScheduleDt = pmtScheduleDt;
       this.amount = amount;
       this.pmtStatus = pmtStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="pmt_id", unique=true, nullable=false)
    public Integer getPmtId() {
        return this.pmtId;
    }
    
    public void setPmtId(Integer pmtId) {
        this.pmtId = pmtId;
    }
    @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="payee_id", nullable=false)
    public Payee getPayee() {
        return this.payee;
    }
    
    public void setPayee(Payee payee) {
        this.payee = payee;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="pmt_schedule_dt", nullable=false, length=10)
    public Date getPmtScheduleDt() {
        return this.pmtScheduleDt;
    }
    
    public void setPmtScheduleDt(Date pmtScheduleDt) {
        this.pmtScheduleDt = pmtScheduleDt;
    }
    
    @Column(name="amount", nullable=false, precision=7)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
    @Column(name="pmt_status", nullable=false, length=40)
    public String getPmtStatus() {
        return this.pmtStatus;
    }
    
    public void setPmtStatus(String pmtStatus) {
        this.pmtStatus = pmtStatus;
    }

    @Column(nullable = false, updatable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @CreatedDate
    private Date createdAt;

    @Column(nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @LastModifiedDate
    private Date updatedAt;


}


