package hashpp.bills.model;
// Generated Dec 2, 2019 12:32:32 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * BillSchedules generated by hbm2java
 */
@Entity
@Table(name="bill_schedules"
    ,catalog="billpay"
)
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(value = {"createdAt", "updatedAt", "payees"},
        allowGetters = true)
public class BillSchedules  implements java.io.Serializable {


     private String billSchId;
     private String scheduleName;
     private String frequency;
     private Set<Payee> payees = new HashSet<Payee>(0);

    public BillSchedules() {
    }

	
    public BillSchedules(String billSchId, String scheduleName) {
        this.billSchId = billSchId;
        this.scheduleName = scheduleName;
    }
    public BillSchedules(String billSchId, String scheduleName, String frequency, Set<Payee> payees) {
       this.billSchId = billSchId;
       this.scheduleName = scheduleName;
       this.frequency = frequency;
       this.payees = payees;
    }
   
     @Id 
    
    @Column(name="bill_sch_id", unique=true, nullable=false, length=3)
    public String getBillSchId() {
        return this.billSchId;
    }
    
    public void setBillSchId(String billSchId) {
        this.billSchId = billSchId;
    }
    
    @Column(name="schedule_name", nullable=false, length=40)
    public String getScheduleName() {
        return this.scheduleName;
    }
    
    public void setScheduleName(String scheduleName) {
        this.scheduleName = scheduleName;
    }
    
    @Column(name="frequency", length=40)
    public String getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="billSchedules")
    public Set<Payee> getPayees() {
        return this.payees;
    }

    public void setPayees(Set<Payee> payees) {
        this.payees = payees;
    }

    @Column(nullable = false, updatable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @CreatedDate
    private Date createdAt;

    @Column(nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @LastModifiedDate
    private Date updatedAt;


}


