package hashpp.bills.model;
// Generated Dec 2, 2019 12:32:32 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * PaymentMethods generated by hbm2java
 */
@Entity
@Table(name="payment_methods"
    ,catalog="billpay"
)
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(value = {"createdAt", "updatedAt", "payees"},
        allowGetters = true)
public class PaymentMethods  implements java.io.Serializable {


     private String pmtMethodId;
     private String methodName;
     private Set<Payee> payees = new HashSet<Payee>(0);

    public PaymentMethods() {
    }

	
    public PaymentMethods(String pmtMethodId, String methodName) {
        this.pmtMethodId = pmtMethodId;
        this.methodName = methodName;
    }
    public PaymentMethods(String pmtMethodId, String methodName, Set<Payee> payees) {
       this.pmtMethodId = pmtMethodId;
       this.methodName = methodName;
       this.payees = payees;
    }
   
     @Id 
    
    @Column(name="pmt_method_id", unique=true, nullable=false, length=3)
    public String getPmtMethodId() {
        return this.pmtMethodId;
    }
    
    public void setPmtMethodId(String pmtMethodId) {
        this.pmtMethodId = pmtMethodId;
    }
    
    @Column(name="method_name", nullable=false, length=40)
    public String getMethodName() {
        return this.methodName;
    }
    
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="paymentMethods")
    public Set<Payee> getPayees() {
        return this.payees;
    }

    public void setPayees(Set<Payee> payees) {
        this.payees = payees;
    }

    @Column(nullable = false, updatable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @CreatedDate
    private Date createdAt;

    @Column(nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @LastModifiedDate
    private Date updatedAt;


}


